train1/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
resources :articles
 root 'welcome#index'
end

train1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

train1/app/models/article.rb
class Article < ApplicationRecord
end

train1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

train1/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 def index
    @articles = Article.all
  end
def show
    @article = Article.find(params[:id])
  end 
def new
  end
def create
  @article = Article.new(article_params)
 
  @article.save
  redirect_to @article
end
 
private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

train1/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

train1/app/helpers/application_helper.rb
module ApplicationHelper
end

train1/app/helpers/articles_helper.rb
module ArticlesHelper
end

train1/app/helpers/welcome_helper.rb
module WelcomeHelper
end

train1/app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
 
    <tr>
 <% @articles.each do |article| %> 
     <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

train1/app/views/articles/new.html.erb
<h1>New Article</h1>


<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

train1/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

train1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Train1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

train1/app/views/welcome/index.html.erb
<h1 style="size: 90"><b>NEW ARTICLE</b></h1>
<br>
<br>
TITLE<br>
<input type="text" name="t1">
<br>
<br>
TEXT<br>
<textarea rows="10" cols="10"></textarea>
<br><br>
<input type="submit" name="submit" value="SAVE ARTICLE">